name: Build HideMT APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Fix permission
        run: chmod +x gradlew

      # 强制使用稳定 Gradle 8.7 不使用9.4.1
      - name: Build Release APK
        run: |
          ./gradlew wrapper --gradle-version=8.7
          ./gradlew clean assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HideMT-Release
          path: app/build/outputs/apk/release/app-release-unsigned.apk
